-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Real Estate Deal Evaluator Schema
-- Description: Auto-generated database schema for Real Estate Deal Evaluator. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS property_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  address VARCHAR(255),
  purchase_price DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE property_info IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Property_info';

CREATE TABLE IF NOT EXISTS financing_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  loan_amount DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE financing_info IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Financing_info';

CREATE TABLE IF NOT EXISTS expense_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  property_tax DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE expense_info IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Expense_info';

CREATE TABLE IF NOT EXISTS cap_rate (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  cap_rate DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cap_rate IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Cap_rate';

CREATE TABLE IF NOT EXISTS irr (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  irr DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE irr IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Irr';

CREATE TABLE IF NOT EXISTS cash_flow (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  cash_flow DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cash_flow IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Cash_flow';

CREATE TABLE IF NOT EXISTS annual_projections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  year INTEGER,
  rental_income DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE annual_projections IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Annual_projections';

CREATE TABLE IF NOT EXISTS financial_visualization (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  metric_name VARCHAR(255),
  value DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE financial_visualization IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Financial_visualization';

CREATE TABLE IF NOT EXISTS scenario_comparison (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id INTEGER,
  scenario_type VARCHAR(255),
  comparison_value DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE scenario_comparison IS 'Schema: Real Estate Deal Evaluator Schema - Entity: Scenario_comparison';

